"""add board owner

Revision ID: fa34d56a3916
Revises: baf7a0bdaf7e
Create Date: 2026-09-30 20:03:16.174358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa34d56a3916'
down_revision: Union[str, Sequence[str], None] = 'baf7a0bdaf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'boards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_column('boards', 'user_id')
    # ### end Alembic commands ###
